package com.anelsoftware.beer.domain.enumeration;

/**
 * The Provincia enumeration.
 */
public enum Provincia {
    MISIONES,  SAN_LUIS,  SAN_JUAN,  ENTRE_RÍOS,  SANTA_CRUZ,  RÍO_NEGRO,  CHUBUT,  CÓRDOBA,  MENDOZA,  LA_RIOJA,  CATAMARCA,  LA_PAMPA,  SANTIAGO_DEL_ESTERO,  CORRIENTES,  SANTA_FE,  TUCUMÁN,  NEUQUÉN,  SALTA,  CHACO,  FORMOSA,  JUJUY,  CIUDAD_AUTÓNOMA_DE_BUENOS_AIRES,  BUENOS_AIRES,  TIERRA_DEL_FUEGO,   ANTÁRTIDA_E_ISLAS_DEL_ATLÁNTICO_SUR
}
